name: journey_plotter2
dependencies:
    - python==3.11
    - geopandas==0.8.2
    - gpxpy==1.3.4
    - shapely==1.6.4
    - pip==20.2.2
    - pip:
        - opencv-python==3.4.4.19
        - matplotlib==3.0.2